#!/bin/sh -ex

get_git()
{
  if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
      DIRTY="-dirty"
  fi

  COMMIT=$(git rev-parse --short HEAD)
}


get_git
DATE=$(date +%Y%m%d)

export OS_REPO=rancher/harvester-os
export OS_LABEL="base-${DATE}"
export OS_VERSION=${DATE}
export OS_GIT="${COMMIT}${DIRTY}"

envsubst >os-release <os-release.tmpl
