#!/bin/sh -e

source $(dirname $0)/version

export OS_NAME=Harvester
export OS_REPO=rancher/harvester-os
export OS_LABEL="${VERSION}"
export OS_VERSION=${VERSION}

envsubst >os-release <os-release.tmpl

echo "==============="
echo "OS release info"
echo "==============="
cat os-release
